#!/usr/bin/env python3
"""
build_icons.py – Convert PNG images to RGB565 C++ byte arrays.

Usage:
    python tools/build_icons.py <input.png> [input2.png ...] -o <output.h>

Requires Pillow:
    pip install Pillow

Each image is converted to a uint16_t array in RGB565 big-endian format,
suitable for use with MatrixPanel_I2S_DMA::drawRGBBitmap().

Example output:
    // 16x16 icon, 256 pixels
    static const uint16_t icon_name[256] PROGMEM = { 0xF800, ... };
"""

import argparse
import os
import sys


def png_to_rgb565(path: str) -> tuple[str, list[int], int, int]:
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is not installed. Run: pip install Pillow")

    img = Image.open(path).convert("RGB")
    w, h = img.size
    pixels = list(img.getdata())

    rgb565 = []
    for r, g, b in pixels:
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        rgb565.append(value)

    name = os.path.splitext(os.path.basename(path))[0]
    # Sanitise name: replace non-alphanumeric with underscore
    name = "".join(c if c.isalnum() else "_" for c in name)
    return name, rgb565, w, h


def generate_header(images: list[tuple[str, list[int], int, int]]) -> str:
    lines = [
        "// Auto-generated by tools/build_icons.py – do not edit manually.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    for name, pixels, w, h in images:
        count = len(pixels)
        lines.append(f"// {w}x{h} pixels ({count} values)")
        hex_values = ", ".join(f"0x{v:04X}" for v in pixels)
        lines.append(
            f"static const uint16_t icon_{name}[{count}] PROGMEM = {{ {hex_values} }};"
        )
        lines.append(f"static const uint8_t icon_{name}_w = {w};")
        lines.append(f"static const uint8_t icon_{name}_h = {h};")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="PNG → RGB565 C++ array converter")
    parser.add_argument("inputs", nargs="+", metavar="INPUT.PNG")
    parser.add_argument("-o", "--output", default="icons.h", metavar="OUTPUT.H")
    args = parser.parse_args()

    images = []
    for path in args.inputs:
        if not os.path.isfile(path):
            sys.exit(f"File not found: {path}")
        print(f"Converting {path} …")
        images.append(png_to_rgb565(path))

    header = generate_header(images)
    with open(args.output, "w") as f:
        f.write(header)
    print(f"Written: {args.output} ({len(images)} image(s))")


if __name__ == "__main__":
    main()
